version: '3'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - responder1
      - responder2

  responder1:
    build: .
    expose:
      - "8000"

  responder2:
    build: .
    expose:
      - "8000"